
service: pruebacontinua

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    timeout: 60
    memorySize: 128
